<?php
function o($text)
{
    echo htmlspecialchars($text);
}
?><?php if ($fullhtml): ?>
<html>
    <head>
        <title><?php o($errtype); ?>: <?php o($message); ?></title>
    </head>
<body>
<?php endif ?>
<style type="text/css">
<?php include 'nice_error.css'; ?>
</style>
<div class="nice_error">
    <div class="header">Application error - <?php o($errtype); ?></div>
    <div class="description">
        <table>
            <tr>
                <td>File:</td>
                <td><?php o($file); ?></td>
            </tr>
            <tr>
                <td>Line:</td>
                <td><?php o($line); ?></td>
            </tr>
            <tr>
                <td>Description:</td>
                <td><?php o($message); ?></td>
            </tr>
            <?php if ($display_backtrace): ?>
            <tr>
                <td>Backtrace:</td>
                <td>
                    <ol>
                    <?php foreach ($backtrace as $trace): ?>
                        <?php if (isset($trace['file']) && $trace['file']): ?>
                        <li>
                            <span><?php o($trace['file']); ?>:<?php o($trace['line']); ?></span>
                            <?php if (isset($trace['function']) && $trace['function']): ?>
                            <span>- <span>
                            <b>
                                <?php if (isset($trace['class']) && $trace['class']): ?>
                                    <span><?php o($trace['class']); ?></span><span><?php o($trace['type']); ?></span><span><?php o($trace['function']); ?></span>
                                <?php else: ?>
                                    <span><?php o($trace['function']); ?></span>
                                <?php endif ?>
                            </b>
                            <?php endif ?>
                        </li>
                        <?php endif ?>
                    <?php endforeach ?>
                    </ol>
                </td>
            </tr>
            <?php endif ?>
        </table>
    </div>
    <?php if ($display_source): ?>
    <div class="source">
        <table>
        <?php foreach ($source as $s_line): ?>
            <?php if ($s_line['num'] == $line) :?>
            <tr class="error-line">
            <?php else: ?>
            <tr>
            <?php endif ?>
                <td class="source-num"><?php o($s_line['num']); ?></td>
                <td class="source-text">
                    <pre><?php o($s_line['text']); ?></pre>
                </td>
            </tr>
        <?php endforeach ?>
        </table>
    </div>
    <?php endif ?>
</div>

<style type="text/css">
</style>
<script type="text/javascript">
<?php include 'nice_error.js'; ?>
</script>
<?php if ($fullhtml): ?>
</body>
</html>
<?php endif ?>
