<!doctype html>
<html>
    <head>
        <title><?= $h($errtype); ?>: <?= $h($message); ?></title>
        <link rel="icon" type="image/png" href="<?php include 'favicon.ico'; ?>">
    </head>
    <body>
        <style type="text/css">
        <?php include 'nice_error.css'; ?>
        </style>
        <div>
            <h1>Application error: <?= $h($errtype) ?></h1>
            <h3><?= $h($message) ?></h3>
            <table>
                <tr>
                    <td class="files">
                        <div>
                            <?php foreach ($backtrace as $i => $trace): ?>
                            <?php if ($i === 0): ?>
                            <article class="selected">
                            <?php else: ?>
                            <article>
                            <?php endif ?>
                                <?php if ($s($trace, 'class') || $s($trace, 'function')): ?>
                                <section>
                                    <?php if ($s($trace, 'class')): ?>
                                    <span><?= $trace['class'] ?></span>
                                    <?php endif ?>
                                    <?php if ($s($trace, 'function')): ?>
                                    <span><?= $trace['function'] ?></span>
                                    <?php endif ?>
                                </section>
                                <?php else: ?>
                                <section>
                                    <span class="call-class">{script}</span>
                                </section>
                                <?php endif ?>
                                <section>
                                    <span><?= $trace['file'] ?></span><span>:</span><span><?= $trace['line'] ?></span>
                                </section>
                            </article>
                            <?php endforeach ?>
                        </div>
                    </td>
                    <td class="source">
                        <article>
                            <?php foreach ($backtrace as $trace): ?>
                            <section>
                                <header>
                                    <h2><?= $h($trace['file']) ?></h2>
                                </header>
                                <table>
                                <?php foreach ($source($trace['file'], $trace['line'], 10) as $s_line): ?>
                                    <?php if ($s_line['num'] == $trace['line']) :?>
                                    <tr class="source-error">
                                    <?php else: ?>
                                    <tr>
                                    <?php endif ?>
                                        <td><?php $o($s_line['num']); ?></td>
                                        <td>
                                            <pre><?php $o($s_line['text']); ?></pre>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                                </table>
                            </section>
                            <?php endforeach ?>
                        </article>
                    </td>
                </tr>
            </table>
        </div>
        <script type="text/javascript">
        <?php include 'nice_error.js'; ?>
        </script>
    </body>
</html>
