<!doctype html>
<html>
<?php

$o = function($text) {
    echo htmlspecialchars($text);
};

$h = function($text) {
    return htmlspecialchars($text);
};

$s = function($obj, $key) {
    return isset($obj[ $key ]) && $obj[ $key ];
};

$source = function($file, $line, $offset = 10) {
    $source = [];

    if (file_exists($file) && is_readable($file)) {
        $lines = explode(PHP_EOL, file_get_contents($file));
        $i = $line - $offset;
        $max = $line + $offset + 1;

        for (; $i < $max; $i++)
            if (isset($lines[ $i - 1 ]))
                $source[] = [
                    'text' => $lines[ $i - 1 ],
                    'num' => $i,
                ];
    }

    return $source;
};

?>
    <head>
        <title><?= $h($error->errtype); ?>: <?= $h($error->message); ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="icon" type="image/png" href="<?php include 'favicon.ico'; ?>">
    </head>
    <body>
        <style type="text/css">
        <?php include 'styles.css'; ?>
        </style>
        <div>
            <h1>Application error: <?= $h($error->errtype) ?></h1>
            <h3><?= $h($error->message) ?></h3>
            <table>
                <tr>
                    <td class="files">
                        <div>
                            <?php foreach ($error->backtrace as $i => $trace): ?>
                            <?php if ($i === 0): ?>
                            <article class="selected">
                            <?php else: ?>
                            <article>
                            <?php endif ?>
                                <?php if ($s($trace, 'class') || $s($trace, 'function')): ?>
                                <section>
                                    <?php if ($s($trace, 'class')): ?>
                                    <span><?= $trace['class'] ?></span>
                                    <?php endif ?>
                                    <?php if ($s($trace, 'function')): ?>
                                    <span><?= $trace['function'] ?></span>
                                    <?php endif ?>
                                </section>
                                <?php else: ?>
                                <section>
                                    <span class="call-class">{script}</span>
                                </section>
                                <?php endif ?>
                                <?php if ($s($trace, 'file') || $s($trace, 'line')): ?>
                                <section>
                                    <?php if ($s($trace, 'file')): ?>
                                    <span title="<?= $h($trace['file']) ?>">
                                    <?= str_replace(getcwd() . DIRECTORY_SEPARATOR, '', $trace['file']) ?>
                                    <?php else: ?>
                                    <span>
                                    <?php endif ?>
                                    </span><span>:</span><span>
                                    <?php if ($s($trace, 'line')): ?>
                                    <?= $trace['line'] ?>
                                    <?php endif ?>
                                    </span>
                                </section>
                                <?php endif ?>
                            </article>
                            <?php endforeach ?>
                        </div>
                    </td>
                    <td class="source">
                        <article>
                            <?php foreach ($error->backtrace as $trace): ?>
                            <section>
                                <header>
                                    <?php if ($s($trace, 'file')): ?>
                                    <h2><?= $h($trace['file']) ?></h2>
                                    <?php endif ?>
                                </header>
                                <table>
                                <?php if ($s($trace, 'file') && $s($trace, 'line')): ?>
                                <?php foreach ($source($trace['file'], $trace['line'], 10) as $s_line): ?>
                                    <?php if ($s_line['num'] == $trace['line']) :?>
                                    <tr class="source-error">
                                    <?php else: ?>
                                    <tr>
                                    <?php endif ?>
                                        <td><?php $o($s_line['num']); ?></td>
                                        <td>
                                            <pre><?php $o($s_line['text']); ?></pre>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                                <?php endif ?>
                                </table>
                            </section>
                            <?php endforeach ?>
                        </article>
                    </td>
                </tr>
            </table>
        </div>
        <script type="text/javascript">
        <?php include 'javascript.js'; ?>
        </script>
    </body>
</html>
